"""add chat-id

Revision ID: 3953e9055567
Revises: 973a4bd9169a
Create Date: 2020-03-15 16:05:16.964045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3953e9055567'
down_revision = '973a4bd9169a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'chat_id')
    # ### end Alembic commands ###
