"""del chat-id

Revision ID: 973a4bd9169a
Revises: f8b9eed2688a
Create Date: 2020-03-15 16:04:28.559078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973a4bd9169a'
down_revision = 'f8b9eed2688a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
