"""Change type chat_id in Channel

Revision ID: f8b9eed2688a
Revises: e6e7a2ec523b
Create Date: 2020-03-15 16:03:00.212331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b9eed2688a'
down_revision = 'e6e7a2ec523b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
